### ISSUE TITLE
SCSS compilation error when migration from 9.4.6 to 10.0.5

### ISSUE THREAD

**Issue by eduardomozart** [glpi-project/glpi#13340]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.4.6 -> 10.0.5

### Bug description

When loading the Setup through the Web browser after extracting the GLPI 10.0.5 files overwriting the files from GLPI 9.4.6, the following errors is shown at the page:

````
An error occurred during SCSS compilation: It's not clear which file to import. Found:
C:/inetpub/glpi/css/palettes/_flood.scss
C:/inetpub/glpi/css/palettes/flood.scss:C:/inetpub/glpi/css/palettes on line 1, at column 0
````

````
An error occurred during SCSS compilation: It's not clear which file to import. Found:
C:/inetpub/glpi/css/palettes/_flood.scss
C:/inetpub/glpi/css/palettes/flood.scss:C:/inetpub/glpi/css/palettes on line 1, at column 0
````

The CSS from the page isn't load, as can be seen into the screenshot below:

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/2974895/202783503-e37fc5b9-769a-4c20-8f84-47cfc3dd17db.png">

### Relevant log output

```shell
``php-error.log`` output:

`
[2022-11-18 15:56:57] glpiphplog.WARNING: Test logger  
[2022-11-18 15:56:57] glpiphplog.DEBUG: Html::compileScss() in C:\inetpub\glpi\src\Html.php line 6855
Compile css/palettes/flood.scss  {"user":"@UNIFI"} 
[2022-11-18 15:56:57] glpiphplog.CRITICAL:   *** Uncaught Exception ScssPhp\ScssPhp\Exception\CompilerException: It's not clear which file to import. Found:
  C:/inetpub/glpi/css/palettes/_flood.scss
  C:/inetpub/glpi/css/palettes/flood.scss: C:/inetpub/glpi/css/palettes on line 1, at column 0 in C:\inetpub\glpi\vendor\scssphp\scssphp\src\Compiler.php at line 6102
  Backtrace :
  vendor\scssphp\scssphp\src\Compiler.php:5917       ScssPhp\ScssPhp\Compiler->error()
  vendor\scssphp\scssphp\src\Compiler.php:5884       ScssPhp\ScssPhp\Compiler->checkImportPathConflicts()
  vendor\scssphp\scssphp\src\Compiler.php:5859       ScssPhp\ScssPhp\Compiler->resolveImportPath()
  vendor\scssphp\scssphp\src\Compiler.php:2699       ScssPhp\ScssPhp\Compiler->findImport()
  vendor\scssphp\scssphp\src\Compiler.php:2915       ScssPhp\ScssPhp\Compiler->compileImport()
  vendor\scssphp\scssphp\src\Compiler.php:2378       ScssPhp\ScssPhp\Compiler->compileChild()
  vendor\scssphp\scssphp\src\Compiler.php:744        ScssPhp\ScssPhp\Compiler->compileChildrenNoReturn()
  vendor\scssphp\scssphp\src\Compiler.php:522        ScssPhp\ScssPhp\Compiler->compileRoot()
  src\Html.php:6856                                  ScssPhp\ScssPhp\Compiler->compileString()
  front\css.php:59                                   Html::compileScss()
  
[2022-11-18 15:57:42] glpiphplog.DEBUG: Html::compileScss() in C:\inetpub\glpi\src\Html.php line 6855
Compile css/palettes/flood.scss  {"user":"@UNIFI"} 
[2022-11-18 15:57:42] glpiphplog.CRITICAL:   *** Uncaught Exception ScssPhp\ScssPhp\Exception\CompilerException: It's not clear which file to import. Found:
  C:/inetpub/glpi/css/palettes/_flood.scss
  C:/inetpub/glpi/css/palettes/flood.scss: C:/inetpub/glpi/css/palettes on line 1, at column 0 in C:\inetpub\glpi\vendor\scssphp\scssphp\src\Compiler.php at line 6102
  Backtrace :
  vendor\scssphp\scssphp\src\Compiler.php:5917       ScssPhp\ScssPhp\Compiler->error()
  vendor\scssphp\scssphp\src\Compiler.php:5884       ScssPhp\ScssPhp\Compiler->checkImportPathConflicts()
  vendor\scssphp\scssphp\src\Compiler.php:5859       ScssPhp\ScssPhp\Compiler->resolveImportPath()
  vendor\scssphp\scssphp\src\Compiler.php:2699       ScssPhp\ScssPhp\Compiler->findImport()
  vendor\scssphp\scssphp\src\Compiler.php:2915       ScssPhp\ScssPhp\Compiler->compileImport()
  vendor\scssphp\scssphp\src\Compiler.php:2378       ScssPhp\ScssPhp\Compiler->compileChild()
  vendor\scssphp\scssphp\src\Compiler.php:744        ScssPhp\ScssPhp\Compiler->compileChildrenNoReturn()
  vendor\scssphp\scssphp\src\Compiler.php:522        ScssPhp\ScssPhp\Compiler->compileRoot()
  src\Html.php:6856                                  ScssPhp\ScssPhp\Compiler->compileString()
  front\css.php:59                                   Html::compileScss()
  
````

``sql-error.log``:

```
[2022-11-18 15:56:57] glpisqllog.ERROR: DBmysql::query() in C:\inetpub\glpi\src\DBmysql.php line 370
  *** MySQL query error:
  SQL: SELECT `id`, `entities_id`, `enable_custom_css` FROM `glpi_entities` WHERE `id` IN ('0')
  Error: Unknown column 'enable_custom_css' in 'field list'
  Backtrace :
  src\DBmysqlIterator.php:112                        
  src\DBmysql.php:1056                               DBmysqlIterator->execute()
  src\Entity.php:3221                                DBmysql->request()
  src\Entity.php:2553                                Entity::getUsedConfig()
  ...\View\Extension\FrontEndAssetsExtension.php:168 Entity->getCustomCssTag()
  ...34031659ba78c6eceb60280add24f5bd3b677db1.php:86 Glpi\Application\View\Extension\FrontEndAssetsExtension->customCss()
  vendor\twig\twig\src\Template.php:394              __TwigTemplate_689c139ef583f0a66f03cfd76fc194feb96c77301a19936fe7779d8314609d5c->doDisplay()
  vendor\twig\twig\src\Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor\twig\twig\src\TemplateWrapper.php:47        Twig\Template->display()
  src\Application\View\TemplateRenderer.php:179      Twig\TemplateWrapper->display()
  src\Html.php:1397                                  Glpi\Application\View\TemplateRenderer->display()
  src\Html.php:2144                                  Html::includeHeader()
  inc\config.php:191                                 Html::nullHeader()
  inc\includes.php:53                                include_once()
  index.php:89                                       include()
  {"user":"@UNIFI"} 
[2022-11-18 15:56:57] glpisqllog.ERROR: DBmysql::query() in C:\inetpub\glpi\src\DBmysql.php line 370
  *** MySQL query error:
  SQL: SELECT `id`, `entities_id`, `enable_custom_css`, `custom_css_code` FROM `glpi_entities` WHERE `id` IN ('0')
  Error: Unknown column 'enable_custom_css' in 'field list'
  Backtrace :
  src\DBmysqlIterator.php:112                        
  src\DBmysql.php:1056                               DBmysqlIterator->execute()
  src\Entity.php:3221                                DBmysql->request()
  src\Entity.php:2563                                Entity::getUsedConfig()
  ...\View\Extension\FrontEndAssetsExtension.php:168 Entity->getCustomCssTag()
  ...34031659ba78c6eceb60280add24f5bd3b677db1.php:86 Glpi\Application\View\Extension\FrontEndAssetsExtension->customCss()
  vendor\twig\twig\src\Template.php:394              __TwigTemplate_689c139ef583f0a66f03cfd76fc194feb96c77301a19936fe7779d8314609d5c->doDisplay()
  vendor\twig\twig\src\Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor\twig\twig\src\TemplateWrapper.php:47        Twig\Template->display()
  src\Application\View\TemplateRenderer.php:179      Twig\TemplateWrapper->display()
  src\Html.php:1397                                  Glpi\Application\View\TemplateRenderer->display()
  src\Html.php:2144                                  Html::includeHeader()
  inc\config.php:191                                 Html::nullHeader()
  inc\includes.php:53                                include_once()
  index.php:89                                       include()
  {"user":"@UNIFI","mem_usage":"0.007\", 2.92Mio)"} 
```

No error is thrown at PHP errors log (``php-errors.log``).

### Page URL

http://glpi.example.com/

### Steps To reproduce

1. Extract the files from GLPI 10.0.5 overwriting the files from GLPI 9.4.6 from an existing installation.
2. Access the GLPI Setup page through the Web browser.

### Your GLPI setup information

Not available.
Ambient is using IIS + PHP 7.4.33 + MySQL 5.7 + GLPI 10.0.5 into a Windows Server 2012 instance.

### Anything else?

Please let me know if anymore information can be provided to troubleshoot and fix this issue.

**Comment by eduardomozart** [comment]
I noticed that when clicking into the "Update" button to continue, the page (including it's CSS) is loaded as expected.

**Comment by cconard96** [comment]
GLPI should not be updated by copying the new folders/files into an existing GLPI installation. The error indicates you have the old theme files and new ones which are named slightly different but treated the same by the compiler (that's why it doesn't know which to use). Copying new files into an existing installation can also lead to old code files remaining after they are removed from new installations and that could cause unexpected behavior.

Please refer to the official installation documentation on the process for upgrading.
https://glpi-install.readthedocs.io/en/latest/update.html

If you need further help upgrading, feel free to make a post on the forum as we only track bugs on GitHub.
https://forum.glpi-project.org/index.php

**Comment by eduardomozart** [comment]
If someone didn't follow the best practice and ended up here, this problem will continue to happen everytime you open the Login screen after the migration. To fix it, remove all the files that starts with ``_*.scss`` from ``<GLPI_ROOT>\css\palettes``, except the ``_defaults.scss`` file.
